# Generated by Django 4.2.6 on 2023-10-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('students', models.ManyToManyField(to='HW.student')),
            ],
        ),
    ]
