# Generated by Django 4.2.4 on 2023-09-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views_app', '0003_remove_author_tel_author_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('hide', 'Возможность прятать посты'),)},
        ),
    ]
